# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  pull_request:
    branches:
      - main


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        name: Descargando el repo
      - name: Instalar Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '17'
      - name: Instalar el gradle
        uses: gradle/actions/setup-gradle@v3
      - name: Buildiear el proyecto
        run: ./gradlew build
      - uses: mr-smithers-excellent/docker-build-push@v6
        name: Crear y subir la imagen
        with:
          image: miguelfeo/kubernetesback
          tags: latest
          registry: docker.io
          dockerfile: Dockerfile
          username: ${{ secrets.DOCKER_USUARIO }}
          password: ${{ secrets.DOCKER_CLAVE }}

      - name: Install yq and Helm
        run: |
          sudo curl -L https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64 -o /usr/local/bin/yq
          sudo chmod +x /usr/local/bin/yq
          curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash

      - name: Checkout Helm chart repo
        uses: actions/checkout@v4
        with:
          repository: miguelangelfeo/helmchart
          ref: chart
          path: helmchart
          token: ${{ secrets.SECRET_TOKEN }}

      - name: Update Helm chart image tag and version
        run: |
          cd helmchart/apichart
          CURRENT_VERSION=$(yq eval '.version' Chart.yaml)
          NEW_VERSION=$(echo $CURRENT_VERSION | awk -F. '{$NF = $NF + 1;} 1' | sed 's/ /./g')
          yq eval ".version = \"$NEW_VERSION\"" -i Chart.yaml
          
          yq eval ".image.tag = \"${{ github.sha }}\"" -i values.yaml    

      - name: Package Helm chart
        run: |
          cd apichart
          helm package . --destination ../charts

      - name: Prepare gh-pages branch
        run: |
          cd helmchart
          git checkout --orphan gh-pages
          git rm -rf .
          mkdir -p charts/$NEW_VERSION
          cp charts/*.tgz charts/$NEW_VERSION/
          helm repo index charts --url https://miguelangelfeo.github.io/helmchart
            
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add .
          git commit -m "Publish chart version $NEW_VERSION"
          git push origin gh-pages --force

      - name: Push changes to chart repo
        run: |
          cd helmchart
          git add .
          git commit -m "Update chart to version $NEW_VERSION"
          git push